version: "3.8"

services:
  frontend:
    image: nova-iagentek:latest
    networks:
      - iagenteknet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nova.rule=Host(`nova.iagentek.com.mx`)"
        - "traefik.http.routers.nova.entrypoints=websecure"
        - "traefik.http.routers.nova.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.nova.loadbalancer.server.port=80"

networks:
  iagenteknet:
    external: true
